CREATE TYPE user_status AS ENUM ('ACTIVE', 'INACTIVE', 'SUSPENDED');

ALTER TABLE users
ADD COLUMN status user_status DEFAULT 'INACTIVE' NOT NULL;

ALTER TABLE otps
ADD COLUMN is_verified boolean DEFAULT false NOT NULL;